### ISSUE TITLE
关于在新数据上finetune R2L网络

### ISSUE THREAD

**Issue by ax0057** [snap-research/R2L#12]
您好！请问在合成数据上训练好的R2L模型可以合成训练集以外的物体的图像吗？谢谢！

**Comment by MingSun-Tse** [comment]
It can generate new images that are not in the training set -- like, from a view that is not in the training set (this is the definition of Novel View Synthesis task). In this sense, the answer to your question is yes! But note, the model _cannot_ generate a pixel of some spatial point that has never been seen in any of the original training images.
