### ISSUE TITLE
Two questions regarding missing parts in this codebase

### ISSUE THREAD

**Issue by MacLLL** [snap-research/R2L#13]
Hi, authors, thank you for this great work. I have two following questions.
1. I checked this codebase. The current version only provides nerf_v3.2, and the R2L mentioned in paper is missing. Could you provide it? So that I can reproducing the results.
2. Also, this codebase only supports nerf synthetic dataset, some of the configurations are missing for nerf llff dataset. Could you provide the missing part or explain the difference? 
Thank you.

**Comment by MingSun-Tse** [comment]
1. nerf_v3.2 is the same as R2L: see https://github.com/snap-research/R2L/blob/be28bbce3f434fa059039ad9c902dc7fc151ddc9/main.py#L456

2. I think we've already provided the llff configs? see https://github.com/snap-research/R2L/tree/main/configs
