### ISSUE TITLE
Evaluation resolution for DONeRF and LLFF datasets provided in the main paper

### ISSUE THREAD

**Issue by quan5609** [snap-research/R2L#14]
Hi,
Thanks for sharing such awesome work and nicely organized code!
I am researching about the latest methods that accelerate NeRF inference time and performance. 
I have a few questions for a fair comparison between the cited works in my literature review:

1. What are your image resolution configurations for DONeRF and LLFF datasets in your main paper? ( As I saw in the released code and website's videos, the configuration of LLFF is factor 8: 378x504, which is different from factor 4: 756x1008 that you mentioned in your paper.
2. Also, if your configuration in the paper are 800x800 for DONeRF and 756x1008 for LLFF. Can you share how to train a teacher network as good as yours? I think your teacher's NeRF is really good compared to the original NeRF paper.
3. If your configurations are 400x400 and 378x504. Can you share your results on the large resolution if they are available?

I really appreciate your answer. Thank you so much!

**Comment by MingSun-Tse** [comment]
Hi @quan5609 , thanks for your interest in our paper! 

I just double-checked the log and confirm that *all* the reported results in the main paper are **downsampled by 2x**, i.e., for the DONeRF dataset, the resolution is also 400x400, as mentioned in the main paper ("_All images in the synthetic dataset are down-sampled by 2× during training and testing_"). For the LLFF dataset, this one should be a description mistake indeed (I used the default configs in [nerf-pytorch code](https://github.com/yenchenlin/nerf-pytorch) and did not notice this problem...) This said, all the NeRF and DoNeRF results we compared to are at the same resolution, so the comparison per se is still fair -- We shall correct this LLFF resolution description mistake and update the arxiv version at some point. Thanks for letting us know!

For the 800x800 Blender and 756x1008 LLFF results, I may do my best to train the models and update the results as soon as I can. Meanwhile, you can also train the models by yourself, we have released the [800x800 configs](https://github.com/snap-research/R2L/tree/main/configs). 

And, welcome to check out our another paper [MobileR2L](https://snap-research.github.io/MobileR2L/). The results there are all in the larger resolution.

Let me know if you have more questions. Also welcome to cc me through email (wang.huan@northeastern.edu) if you'd like more prompt feedback, as this repo is owned by Snap; I do not very frequently check the issues.
