### ISSUE TITLE
main.py: error: Unable to open config file: configs/lego_noview.txt. Error: No such file or directory

### ISSUE THREAD

**Issue by sharmrit** [snap-research/R2L#5]
CUDA_VISIBLE_DEVICES=0 python main.py --model_name R2L --config configs/lego_noview.txt --n_sample_per_ray 16 --netwidth 256 --netdepth 88 --use_residual --cache_ignore data --trial.ON --trial.body_arch resmlp --pretrained_ckpt R2L_Blender_Models/lego.tar --render_only --render_test --testskip 1 --screen --project Test__R2L_W256D88__blender_lego

Error: 
main.py: error: Unable to open config file: configs/lego_noview.txt. Error: No such file or directory. 

It looks like configs folder is missing

**Comment by MingSun-Tse** [comment]
thanks for the reminder. updated!

**Comment by sharmrit** [comment]
Thanks
