### ISSUE TITLE
Is it possible to train with real data? 

### ISSUE THREAD

**Issue by sumukund** [snap-research/R2L#7]
Using something like COLMAP to generate poses, would it be possible to train real models as opposed to synthetic data? Thank you!

**Comment by MingSun-Tse** [comment]
Hi! we tested our method on the forward-facing real-world dataset (see visual results in the Appendix of our [1st version paper on arxiv](https://arxiv.org/abs/2203.17261v1)), which is using COLMAP to estimate the parameters. So to answer your question, yes!

**Comment by sumukund** [comment]
On any model, synthetic or real data, does R2L generate a mesh (.ply or other formats)?

**Comment by MingSun-Tse** [comment]
No, the current code does not generate a mesh.
