### ISSUE TITLE
The training is very slow. 

### ISSUE THREAD

**Issue by Fangkang515** [snap-research/R2L#8]
Thanks for your great work.

I found that 8 v100 GPUs were used in your paper, but this release code only support single GPU and it is very slow to distill a student model(takes several days). It's there any tricks can reduce the training time? 

thanks again.

**Comment by MingSun-Tse** [comment]
Hi @Fangkang515 , thanks for your interest! The truth is, when we ran the experiments, we also used 1 GPU per experiment (i.e., no data-parallel for now) -- the code we released is what we used for reporting the results. By "8 v100 GPUs" in the paper, we mean running eight experiments. So sorry we cannot help you here... You may add the data parallel scheme yourself. I presume it is not very hard. Best,
